#!/usr/bin/env python3
"""Convert docs/paper_references.bib into BibTeX the 3DV .bst can actually read.

The working bibliography stores authors comma-separated and keeps a `note` field
recording each entry's fact-check verdict. BibTeX needs ` and ` between authors,
and the verdict notes are internal bookkeeping that must not print in a
submission. This converts the former and drops the latter.

It reads the working file and writes docs/3dv/refs.bib. The working file stays
authoritative, so the verdicts are never lost.

    tools/paper_bib_latex.py [--check]
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "docs" / "paper_references.bib"
OUT = REPO / "docs" / "3dv" / "refs.bib"

# LaTeX-special characters that appear in real titles and venues.
ESCAPES = {"&": r"\&", "%": r"\%", "#": r"\#", "_": r"\_"}


def escape(text: str) -> str:
    out = []
    for ch in text:
        out.append(ESCAPES.get(ch, ch))
    return "".join(out)


def authors_to_bibtex(field: str) -> str:
    """`A, B, C` -> `A and B and C`, preserving each name verbatim."""
    names = [n.strip() for n in field.split(",") if n.strip()]
    return " and ".join(names)


def convert(src: str) -> str:
    entries = re.findall(r"@(\w+)\{([^,]+),(.*?)\n\}", src, flags=re.S)
    if not entries:
        raise SystemExit("no parseable entries in the working bibliography")
    lines = ["% Generated by tools/paper_bib_latex.py from docs/paper_references.bib.",
             "% Do not edit here -- edit the working file, which also records each",
             "% entry's fact-check verdict (dropped from this file on purpose).",
             ""]
    for kind, key, body in entries:
        fields = dict(re.findall(r"(\w+)\s*=\s*\{(.*?)\},\n", body + "\n", flags=re.S))
        lines.append(f"@{kind}{{{key.strip()},")
        if "author" in fields:
            lines.append(f"  author    = {{{escape(authors_to_bibtex(fields['author']))}}},")
        if "editor" in fields:
            lines.append(f"  editor    = {{{escape(authors_to_bibtex(fields['editor']))}}},")
        for name in ("title", "booktitle", "year"):
            if name in fields:
                value = " ".join(fields[name].split())
                # keep capitalisation of acronyms and system names
                if name == "title":
                    value = "{" + escape(value) + "}"
                else:
                    value = escape(value)
                lines.append(f"  {name:<9} = {{{value}}},")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    out = convert(SRC.read_text())
    if "--check" in argv:
        if not OUT.is_file() or OUT.read_text() != out:
            print("docs/3dv/refs.bib is stale; re-run tools/paper_bib_latex.py")
            return 1
        print("refs.bib is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(out)
    print(f"    refs.bib  {out.count('@')} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
